Implements getstatus
orbisgis/orbisserver pull request #19
Opened 2017-06-09 12:24 UTC by guiMande

Implementation of GetStatus method, Javadoc and tests. #5

2017-06-09 12:34 UTC, guiMande commented
Do not accept it yet, i forgot something.

2017-06-09 12:55 UTC, guiMande commented
Now it's up to date.

2017-06-09 13:07 UTC, SPalominos requested changes

2017-06-09 13:07 UTC, SPalominos commented on core-server/src/test/java/org/orbisgis/orbisserver/ITTests/InContainerIT.java
> +                        "file:/C:/Users/mande/AppData/Local/Temp/csvToPointsTable.groovy",null);
put the test file in the resources.

2017-06-09 13:39 UTC, guiMande commented on core-server/src/test/java/org/orbisgis/orbisserver/ITTests/InContainerIT.java
> +                        "file:/C:/Users/mande/AppData/Local/Temp/csvToPointsTable.groovy",null);
Actually, this is the path which is displayed with GetCapabilities, a better idea will be to remove this test.

2017-06-12 06:46 UTC, SPalominos commented on core-server/src/test/java/org/orbisgis/orbisserver/ITTests/InContainerIT.java
> +                        "file:/C:/Users/mande/AppData/Local/Temp/csvToPointsTable.groovy",null);
Maybe you could choose a script with a static identifier.

2017-06-12 07:13 UTC, guiMande commented on core-server/src/test/java/org/orbisgis/orbisserver/ITTests/InContainerIT.java
> +                        "file:/C:/Users/mande/AppData/Local/Temp/csvToPointsTable.groovy",null);
That's what i do with `orbisgis:wps:official:deleteRows`

2017-06-12 07:32 UTC, merged